using Gallop;
using LibMMD.Material;
using LibMMD.Model;
using LibMMD.Reader;
using LibMMD.Unity3D;
using LibMMD.Writer;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using UnityEngine;
using UnityEngine.Rendering;
using static BillboardBuilder;
using static LibMMD.Model.Morph;
using static LibMMD.Model.SkinningOperator;
using static LibMMD.Reader.PMXReader;
using System.Linq;
//using UnityGLTF;


public class ModelExporter
{
    static string modelInfo = $"Generated by UmaViewer {Application.version}, Copyright Cygames \nLink : https://github.com/katboi01/UmaViewer";
    const string Tag = "[Export]";

    public static void ExportModel(UmaContainerCharacter container, string path)
    {
        container.SetDynamicBoneEnable(false);
        container.EnablePhysics = false;
        container.UmaFaceAnimator?.Rebind();
        container.UmaAnimator?.Rebind();
        container.EnableEyeTracking = false;
        container.FaceDrivenKeyTarget?.FacialResetAll();
        AddBlendShape(container);
        BuildBillboard(container);

        var textures = TextureExporter.ExportAllTexture(Path.GetDirectoryName(path), container.gameObject);
        RawMMDModel model;
        // Reads both the baked vertices and the bone positions, so the rest pose has to be in place for
        // the whole read. A no-op unless Config.PmxAPoseRestPose is set.
        using (UmaAPose.Enter(container))
        {
            model = ReadPMXModel(container, textures, container.CharaEntry);
        }

        FileStream fileStream = new FileStream(path, FileMode.Create);
        BinaryWriter writer = new BinaryWriter(fileStream);
        var config = new ModelConfig() { GlobalToonPath = "Toon" };
        PMXWriter.Write(writer, model, config);

        writer.Close();
        fileStream.Close();

        RemoveBillboard(container);
        ClearBlendShape(container);
        UmaViewerUI.Instance.ShowMessage($"PMX Save at {path}", UIMessageType.Success);
    }

    public static void ExportModel(UmaContainer container, string path)
    {

        var textures = TextureExporter.ExportAllTexture(Path.GetDirectoryName(path), container.gameObject);
        var model = ReadPMXModel(container, textures);

        // Vertex index size fix
        PmxConfig pmxConfig = new PmxConfig()
            {
                Utf8Encoding = false,
                Encoding = Encoding.Unicode,
                ExtraUvNumber = 3, //include uv2 and color
                VertexIndexSize = model.Vertices.Length > 65535 ? 4 : (model.Vertices.Length > 255 ? 2 : 1),
                TextureIndexSize = model.TextureList.Count > 255 ? 2 : 1,
                MaterialIndexSize = model.Parts.Length > 255 ? 2 : 1,
                BoneIndexSize = model.Bones.Length > 65535 ? 4 : (model.Bones.Length > 255 ? 2 : 1),
                MorphIndexSize = model.Morphs.Length > 65535 ? 4 : (model.Morphs.Length > 255 ? 2 : 1),
                RigidBodyIndexSize = model.Rigidbodies.Length > 65535 ? 4 : (model.Rigidbodies.Length > 255 ? 2 : 1)
            };

        FileStream fileStream = new FileStream(path, FileMode.Create);
        BinaryWriter writer = new BinaryWriter(fileStream);
        var config = new ModelConfig() { GlobalToonPath = "Toon" };
        PMXWriter.Write(writer, model, config, pmxConfig);

        writer.Close();
        fileStream.Close();

        UmaViewerUI.Instance.ShowMessage($"PMX Save at {path}", UIMessageType.Success);
    }

    public static RawMMDModel ReadPMXModel(UmaContainer container, string[] textures, CharaEntry entry = null)
    {
        RawMMDModel model = new RawMMDModel();
        if (entry != null)
        {
            model.Name = entry.Name;
            model.NameEn = entry.GetName();
            model.Description = model.DescriptionEn = $"{entry.GetName()}\n{modelInfo}";
        }
        else
        {
            model.Name = container.gameObject.name;
            model.NameEn = container.gameObject.name;
            model.Description = model.DescriptionEn = $"{container.gameObject.name}\n{modelInfo}";
        }

        //Rean Bones
        var rootBone = container.transform.Find("Position");
        if (rootBone == null)
        {
            rootBone = container.transform;
        }
        List<Transform> bones = new List<Transform>(rootBone.GetComponentsInChildren<Transform>());
        bones.RemoveAll(o => o.name.Contains("Col_"));

        //Read vertices And triangles
        List<Renderer> renderers = new List<Renderer>(container.GetComponentsInChildren<Renderer>());
        List<int> triangles = new List<int>();
        model.Vertices = ReadVerticesAndTriangles(renderers, bones, ref triangles, container.transform);
        model.TriangleIndexes = triangles.ToArray();

        //Read Texture reference
        foreach (var texture in textures)
        {
            model.TextureList.Add(new MMDTexture(texture));
        }

        model.Parts = ReadPartMaterials(renderers, model);
        model.Bones = ReadBones(bones);
        model.Morphs = ReadMorph(renderers);
        model.Rigidbodies = new MMDRigidBody[0];
        model.Joints = new MMDJoint[0];

        return model;
    }

    public static Vector3[] Vec4ToVec3(Vector4[] vector4s)
    {
        Vector3[] tmp = new Vector3[vector4s.Length];
        for (int i = 0; i < vector4s.Length; i++)
        {
            tmp[i] = new Vector3(vector4s[i].x, vector4s[i].y, vector4s[i].z);
        }
        return tmp;
    }

    public static Vector3[] CalDelta(Vector3[] ori, Vector3[] end)
    {
        Vector3[] tmp = new Vector3[ori.Length];
        for (int i = 0; i < ori.Length; i++)
        {
            tmp[i] = end[i] - ori[i];
        }
        return tmp;
    }

    private static void AddBlendShape(UmaContainerCharacter container)
    {
        if (!container.FaceDrivenKeyTarget) return;
        SkinnedMeshRenderer faceMesh = null;
        SkinnedMeshRenderer eyebrowMesh = null;
        SkinnedMeshRenderer earMesh = null;
        foreach (SkinnedMeshRenderer s in container.GetComponentsInChildren<SkinnedMeshRenderer>())
        {
            if (s.name.Equals("M_Face")) faceMesh = s;
            else if (s.name.Equals("M_Mayu")) eyebrowMesh = s;
            else if (s.name.Equals("M_Hair")) earMesh = s;
        }

        var facial = container.FaceDrivenKeyTarget;
        Action<SkinnedMeshRenderer, List<FacialMorph>, Mesh> addBlendShapePart = delegate (SkinnedMeshRenderer skin, List<FacialMorph> morphs, Mesh baseMesh)
        {
            container.FaceOverrideData = null;
            foreach (var morph in morphs)
            {
                facial.ClearAllWeights();
                morph.weight = 1;
                facial.ChangeMorph();

                Mesh deltaMesh = new Mesh();
                skin.BakeMesh(deltaMesh);
                skin.sharedMesh.AddBlendShapeFrame( $"{morph.name}({morph.tag})[{skin.name}]", 1,
                        CalDelta(baseMesh.vertices, deltaMesh.vertices),
                        CalDelta(baseMesh.normals, deltaMesh.normals),
                        CalDelta(Vec4ToVec3(baseMesh.tangents), Vec4ToVec3(deltaMesh.tangents)));
            }
        };

        if (faceMesh)
        {
            Mesh basefaceMesh = new Mesh();
            faceMesh.BakeMesh(basefaceMesh);
            addBlendShapePart(faceMesh, facial.EyeBrowMorphs, basefaceMesh);
            addBlendShapePart(faceMesh, facial.EyeMorphs, basefaceMesh);
            addBlendShapePart(faceMesh, facial.MouthMorphs, basefaceMesh);
        }
        
        if (eyebrowMesh)
        {
            Mesh baseEyeBrowMesh = new Mesh();
            eyebrowMesh.BakeMesh(baseEyeBrowMesh);
            addBlendShapePart(eyebrowMesh, facial.EyeBrowMorphs, baseEyeBrowMesh);
        }

        if (earMesh)
        {
            Mesh baseEarMesh = new Mesh();
            earMesh.BakeMesh(baseEarMesh);
            addBlendShapePart(earMesh, facial.EarMorphs, baseEarMesh);
        }
            
        facial.ClearAllWeights();
        facial.ChangeMorph();
    }

    private static void ClearBlendShape(UmaContainerCharacter container)
    {
        if (!container.FaceDrivenKeyTarget) return;
        //assuming base meshes do not have any blend shapes
        foreach (SkinnedMeshRenderer s in container.GetComponentsInChildren<SkinnedMeshRenderer>())
        {
            if (s.name.Equals("M_Face") || s.name.Equals("M_Mayu") || s.name.Equals("M_Hair"))
            {
                s.sharedMesh.ClearBlendShapes();
            }
        }
    }

    private static Morph[] ReadMorph(List<Renderer> renderers)
    {
        // Naming is decided in one place so exported models and exported motions agree, see MorphNaming.
        var mode = Config.Instance != null ? Config.Instance.PmxMorphNameMode : PmxMorphNameMode.Unified;

        // Morph name -> accumulated per-vertex offsets. Keyed by name so a morph that exists on
        // several meshes (e.g. the same eyebrow morph baked onto M_Face and M_Mayu) can either be
        // kept apart (tagged names) or merged (the unified/short spellings) depending on the mode.
        Dictionary<string, Morph> morphsByName = new Dictionary<string, Morph>();
        Dictionary<string, Dictionary<int, Vector3>> morphOffsets = new Dictionary<string, Dictionary<int, Vector3>>();
        List<string> morphOrder = new List<string>();
        int vertexOffset = 0;

        foreach (Renderer renderer in renderers)
        {
            Mesh mesh;
            if (renderer is MeshRenderer mr)
            {
                var meshfilter = mr.GetComponent<MeshFilter>();
                mesh = meshfilter.mesh;
            }
            else
            {
                mesh = ((SkinnedMeshRenderer)renderer).sharedMesh;
            }
            var vertexCount = mesh.vertexCount;

            for (int i = 0; i < mesh.blendShapeCount; i++) 
            {
                var deltaVertices = new Vector3[vertexCount];
                var deltaNormals = new Vector3[vertexCount];
                var deltaTangents= new Vector3[vertexCount];
                mesh.GetBlendShapeFrameVertices(i, 0, deltaVertices, deltaNormals, deltaTangents);

                string rawName = mesh.GetBlendShapeName(i);
                MorphNaming.TryParse(rawName, null, out MorphNaming.Parts parts);

                foreach (string morphName in MorphNaming.NamesFor(rawName, null, mode))
                {
                    if (!morphsByName.TryGetValue(morphName, out Morph targetMorph))
                    {
                        targetMorph = new Morph();
                        targetMorph.Name = targetMorph.NameEn = morphName;
                        targetMorph.Type = MorphType.MorphTypeVertex;
                        targetMorph.Category = GetMorphCategory(parts);
                        targetMorph.MorphDatas = new VertexMorphData[0];
                        morphsByName[morphName] = targetMorph;
                        morphOffsets[morphName] = new Dictionary<int, Vector3>();
                        morphOrder.Add(morphName);
                    }

                    var offsets = morphOffsets[morphName];
                    for (int j = 0; j < vertexCount; j++)
                    {
                        // Offset ensures the vertices map to the correct mesh in the combined PMX
                        offsets[vertexOffset + j] = deltaVertices[j];
                    }
                }
            }
            vertexOffset += mesh.vertexCount;
        }

        // Materialise the accumulated offsets, ordered by vertex index so the output is deterministic.
        foreach (string morphName in morphOrder)
        {
            var offsets = morphOffsets[morphName];
            var indices = new List<int>(offsets.Keys);
            indices.Sort();
            var datas = new VertexMorphData[indices.Count];
            for (int i = 0; i < indices.Count; i++)
            {
                datas[i] = new VertexMorphData();
                datas[i].VertexIndex = indices[i];
                datas[i].Offset = offsets[indices[i]];
            }
            morphsByName[morphName].MorphDatas = datas;
        }

        return morphOrder.Select(name => morphsByName[name]).ToArray();
    }

    /// <summary>
    /// Morph categories come from the parsed family, not from the spelling of the exported name:
    /// the unified spelling renames "EyeBrow_*" to "Brow_*", which a name sniff would classify as
    /// "other".
    /// </summary>
    private static MorphCategory GetMorphCategory(MorphNaming.Parts parts)
    {
        switch (parts != null ? parts.Family : null)
        {
            case "Mouth": return MorphCategory.MorphCatMouth;
            case "EyeBrow": return MorphCategory.MorphCatEyebrow;
            case "Eye": return MorphCategory.MorphCatEye;
            default: return MorphCategory.MorphCatOther;
        }
    }

    private static Bone[] ReadBones(List<Transform> bonelist)
    {
        List<Bone> pmxbones = new List<Bone>();
        foreach (var bone in bonelist)
        {
            Bone pmxbone = new Bone();
            pmxbone.Name = pmxbone.NameEn = bone.name;
            pmxbone.Position = bone.position;
            pmxbone.ParentIndex = bonelist.IndexOf(bone.parent);
            pmxbone.TransformLevel = 0;
            pmxbone.Visible = true;
            pmxbone.Movable = true;
            pmxbone.Rotatable = true;
            pmxbone.Controllable = true;
            // A PMX bone's tail is either the index of one of its children or an absolute position. The uma
            // rig has no tails, so a child's head becomes the tail - that is what makes Blender draw the bone
            // along its chain.
            pmxbone.ChildBoneVal = BoneTail(bone, bonelist);
            pmxbones.Add(pmxbone);
        }
        return pmxbones.ToArray();
    }

    /// <summary>
    /// How the tail of one bone is written: the head of a child, or an offset from the bone's own position.
    ///
    /// The child is the first one that describes a direction (see <see cref="PMXTailChild"/>), which is the
    /// next joint for every bone of the body - except where the rig's first child is an attachment that sits
    /// off to the side of the chain, which is what the head bone's children are: its first child is a cheek
    /// offset in front of the face, so the head used to point forward instead of up out of the neck. When the
    /// first child turns more than 60 degrees away from the chain the bone belongs to, the child that really
    /// continues that chain wins instead, at most as long as the segment leading into the bone, so that the
    /// head gets a head-length bone pointing up rather than a spike toward the hair.
    ///
    /// Bones with no usable child at all - finger tips, hair and tail ends, and the roll helpers, whose only
    /// child sits on top of themselves - get a tail along the chain they belong to (<see cref="LeafTail"/>).
    /// </summary>
    private static Bone.ChildBone BoneTail(Transform bone, List<Transform> bonelist)
    {
        Transform pmxChild = PMXTailChild(bone, bonelist);
        Vector3 chain = ChainDirection(bone);
        if (FacesForward(bone))
        {
            // the eyes: their tail points out of the face, not along the chain that arrives at them. The rig's
            // bone axes have forward pointing where the character looks (in the exported file that is -z, where
            // the face helpers sit), and the eye bones themselves hang off the head, so the head's forward is
            // what they look along. See FacesForward.
            Vector3 forward = bone.parent != null ? bone.parent.forward : bone.forward;
            if (forward.sqrMagnitude > 1e-8f)
            {
                float length = chain.sqrMagnitude > 1e-10f ? chain.magnitude * 0.5f : 0.1f;
                return OffsetTail(forward.normalized * length);
            }
        }
        if (pmxChild != null && chain.sqrMagnitude > 1e-10f)
        {
            Vector3 delta = pmxChild.position - bone.position;
            bool offChain = Vector3.Dot(delta.normalized, chain.normalized) < 0.5f;
            if (offChain)
            {
                Transform aligned = AlignedChild(bone, bonelist, chain);
                if (aligned != null)
                {
                    Vector3 direction = aligned.position - bone.position;
                    float length = Mathf.Min(direction.magnitude, chain.magnitude);
                    return OffsetTail(direction.normalized * length);
                }
            }
        }
        if (pmxChild != null)
        {
            return new Bone.ChildBone()
            {
                ChildUseId = true,
                Index = bonelist.IndexOf(pmxChild)
            };
        }
        return OffsetTail(LeafTail(bone));
    }

    private static Bone.ChildBone OffsetTail(Vector3 offset)
    {
        return new Bone.ChildBone()
        {
            ChildUseId = false,
            Index = -1,
            Offset = offset
        };
    }

    /// <summary>
    /// The bones whose tail has to point out of the face instead of along the chain that arrives at them:
    /// the eyeballs and the locators that drive them. MMD points an eye bone at the viewer, so that rotating
    /// it around its own axes moves the gaze - carried along the chain (which comes in from the middle of the
    /// head, up and out towards the temple) a gaze rotation reads as a roll instead, and the eyes look inward.
    /// The direction comes from the bone's own forward axis, which on this rig points where the character
    /// looks; the length stays the same as any other leaf tail, half the segment leading into the bone.
    /// </summary>
    private static bool FacesForward(Transform bone)
    {
        switch (bone.name)
        {
            case "Eye_L":
            case "Eye_R":
            case "Eye_locator_L":
            case "Eye_locator_R":
            case "Eye_target_locator_L":
            case "Eye_target_locator_R":
                return true;
            default:
                return false;
        }
    }

    /// <summary>
    /// The usable child that best continues a chain: the one whose direction lies closest to
    /// <paramref name="chain"/>, and only if it is nearly along it (<see cref="alignedDot"/>). Null when no
    /// child is close enough, which is the case for a bone that really does turn a corner, such as the
    /// shoulder, whose only child is the upper arm.
    /// </summary>
    private static Transform AlignedChild(Transform bone, List<Transform> bonelist, Vector3 chain,
                                          float alignedDot = 0.94f)
    {
        Transform best = null;
        float bestAlignment = alignedDot;
        for (int i = 0; i < bone.childCount; i++)
        {
            Transform child = bone.GetChild(i);
            if (bonelist.IndexOf(child) < 0) continue;
            if (child.name.Contains("_Handle")) continue;
            Transform candidate = child;
            Vector3 delta = candidate.position - bone.position;
            if (delta.sqrMagnitude < 1e-10f)
            {
                // look through a child sitting on the bone, the same way the tail itself does
                candidate = PMXTailChild(child, bonelist, 0);
                if (candidate == null) continue;
                delta = candidate.position - bone.position;
                if (delta.sqrMagnitude < 1e-10f) continue;
            }
            float alignment = Vector3.Dot(delta.normalized, chain.normalized);
            if (alignment > bestAlignment)
            {
                bestAlignment = alignment;
                best = candidate;
            }
        }
        return best;
    }

    /// <summary>
    /// The first child that describes a direction: one that is in the export, not a "_Handle" helper, and not
    /// sitting at the bone's own position. Children that were filtered out of the export (the Col_* colliders)
    /// and the "_Handle" helpers describe no direction at all.
    ///
    /// A child sitting exactly on the bone describes no direction either, but the chain can still continue
    /// through it: the ankle's own children are the ankle offset and the IK handle, both exactly on the ankle,
    /// and the toe that continues the foot hangs off the offset. Looking one level further in matches what a
    /// known-good MMD model does with its ankle - measured on four of them, 足首 points down and forward
    /// towards the toes, never straight down the way the knee segment arrives.
    /// </summary>
    private static Transform PMXTailChild(Transform bone, List<Transform> bonelist, int depth = 1)
    {
        for (int i = 0; i < bone.childCount; i++)
        {
            Transform child = bone.GetChild(i);
            if (bonelist.IndexOf(child) < 0) continue;
            if (child.name.Contains("_Handle")) continue;
            if ((child.position - bone.position).sqrMagnitude > 1e-10f) return child;
            if (depth > 0)
            {
                Transform deeper = PMXTailChild(child, bonelist, depth - 1);
                if (deeper != null) return deeper;
            }
        }
        return null;
    }

    /// <summary>
    /// The direction the chain runs in as it arrives at this bone: the segment from its parent to itself, or
    /// - for a bone sitting exactly on its parent, which is how the uma rig places the roll helpers - the
    /// first ancestor segment that is not degenerate. Zero when there is none, e.g. for the root.
    /// </summary>
    private static Vector3 ChainDirection(Transform bone)
    {
        for (Transform current = bone; current != null; current = current.parent)
        {
            if (current.parent == null) break;
            Vector3 delta = current.position - current.parent.position;
            if (delta.sqrMagnitude > 1e-10f) return delta;
        }
        return Vector3.zero;
    }

    /// <summary>
    /// The tail offset for a bone with nothing usable below it: half of the direction the chain runs in, so
    /// that a finger tip carries on the finger and a roll helper points along the arm or forearm it rolls -
    /// away from the body on both sides, instead of following its own local axes (a mirrored rig does not lay
    /// those out the same way on both sides, which used to point one roll helper at the neck).
    ///
    /// A bone that describes no direction at all (a root, or a bone whose whole ancestry is degenerate) falls
    /// back to the direction of its first child that has one, and otherwise to a short stub, so that there is
    /// always something to draw.
    ///
    /// The value is an offset from the bone's own position, not a position: mmd_tools reads it as
    /// <c>tail = head + offset</c> (core/pmx/importer.py), and its own exporter writes it the same way.
    /// </summary>
    private static Vector3 LeafTail(Transform bone)
    {
        Vector3 segment = ChainDirection(bone);
        if (segment.sqrMagnitude > 1e-10f) return segment * 0.5f;

        for (int i = 0; i < bone.childCount; i++)
        {
            Vector3 delta = bone.GetChild(i).position - bone.position;
            if (delta.sqrMagnitude > 1e-10f) return delta * 0.5f;
        }
        // nothing around it describes a direction: a stub along the bone's own up, which at least keeps the
        // bone visible in a bone list that only stores head, tail and roll
        return bone.up * 0.1f;
    }

    /// <summary>
    /// The exported texture a uma material uses for one of its maps, found in the model's texture list the
    /// same way the albedo is (by file name). Null when the material has no such map, or when the texture
    /// did not make it into the export - the caller decides what to do without it.
    /// </summary>
    private static MMDTexture FindExportedTexture(RawMMDModel model, Material material, string property)
    {
        if (material == null || !material.HasProperty(property)) return null;
        var texture = material.GetTexture(property) as Texture2D;
        if (texture == null) return null;

        var match = model.TextureList.Find(t => t.TexturePath.Contains($"/{texture.name}.png"));
        if (match == null)
        {
            Debug.LogWarning($"{Tag} {material.name}: the {property} texture '{texture.name}' is not in the "
                             + "exported texture list, so that map is missing from the export");
        }
        return match;
    }

    private static float PropertyFloat(Material material, string property, float fallback)
    {
        return material != null && material.HasProperty(property) ? material.GetFloat(property) : fallback;
    }

    private static Color PropertyColour(Material material, string property, Color fallback)
    {
        return material != null && material.HasProperty(property) ? material.GetColor(property) : fallback;
    }

    /// <summary>
    /// The uma shader parameters an MMD material has no field for, written into the material comment as one
    /// line of key=value pairs. mmd_tools imports that comment onto the material
    /// (<c>material.mmd_material.comment</c>), and the uma addon's Shading operator reads it back to set its
    /// shader up with the values this model was exported with instead of its own defaults. Anything that does
    /// not know about it sees a comment, and a property the game renames is skipped rather than breaking the
    /// export - which is also how a rename will be noticed.
    ///
    /// Values use dots for decimals and commas only between the components of a colour, and the numbers are
    /// written with the invariant culture so that a machine with a comma decimal separator cannot produce a
    /// comment that parses as something else.
    /// </summary>
    private static string UmaMaterialComment(Material material, RawMMDModel model)
    {
        if (material == null) return "";

        var comment = new StringBuilder("uma1");
        void Number(string key, string property)
        {
            if (!material.HasProperty(property)) return;
            comment.Append(' ').Append(key).Append('=')
                   .Append(material.GetFloat(property).ToString("0.####", CultureInfo.InvariantCulture));
        }
        void Tint(string key, string property)
        {
            if (!material.HasProperty(property)) return;
            Color colour = material.GetColor(property);
            comment.Append(' ').Append(key).Append('=').Append(string.Join(",",
                colour.r.ToString("0.###", CultureInfo.InvariantCulture),
                colour.g.ToString("0.###", CultureInfo.InvariantCulture),
                colour.b.ToString("0.###", CultureInfo.InvariantCulture),
                colour.a.ToString("0.###", CultureInfo.InvariantCulture)));
        }
        void Map(string key, string property)
        {
            if (!material.HasProperty(property)) return;
            var texture = material.GetTexture(property) as Texture2D;
            if (texture == null) return;
            comment.Append(' ').Append(key).Append('=').Append(texture.name);
        }

        // the shade ramp and the light threshold are what the Blender shader group calls "Shaded Texture"
        // and "Light Threshold"
        Number("toon_step", "_ToonStep");
        Number("toon_feather", "_ToonFeather");
        Number("specular_power", "_SpecularPower");
        Tint("specular", "_SpecularColor");
        Number("env_rate", "_EnvRate");
        Number("env_bias", "_EnvBias");
        Number("rim_step", "_RimStep");
        Number("rim_feather", "_RimFeather");
        Tint("rim", "_RimColor");
        Number("rim_spec_rate", "_RimSpecRate");
        Number("rim_shadow", "_RimShadow");
        Number("outline_width", "_OutlineWidth");
        Tint("outline", "_OutlineColor");
        Tint("chara", "_CharaColor");
        Number("saturation", "_Saturation");
        Tint("toon_bright", "_ToonBrightColor");
        Tint("toon_dark", "_ToonDarkColor");
        Number("emissive_intensity", "_EmissiveIntensity");
        Number("emissive_rim_power", "_EmissiveRimPower");
        Number("emissive_rim_intensity", "_EmissiveRimIntensity");
        Number("use_option_mask", "_UseOptionMaskMap");

        // the maps an MMD material has no field for, by name so the addon does not have to guess file names
        Map("triple", "_TripleMaskMap");
        Map("option", "_OptionMaskMap");
        Map("toon", "_ToonMap");
        Map("env", "_EnvMap");
        Map("emissive", "_EmissiveTex");
        return comment.ToString();
    }

    private static Part[] ReadPartMaterials(List<Renderer> renderers, RawMMDModel model)    {
        List<Part> parts = new List<Part>();
        int baseShift = 0;

        foreach (Renderer renderer in renderers)
        {
            Mesh mesh;
            if (renderer is MeshRenderer mr)
            {
                var meshfilter = mr.GetComponent<MeshFilter>();
                mesh = meshfilter.mesh;
            }
            else
            {
                mesh = ((SkinnedMeshRenderer)renderer).sharedMesh;
            }
            if (!mesh.isReadable)
            {
                try
                {
                    mesh = MakeReadableMeshCopy(mesh);
                }
                catch
                {
                    UmaViewerUI.Instance.ShowMessage($"Skipping material for non-readable mesh: {mesh.name}", UIMessageType.Warning);
                    // Still need to advance baseShift!
                    baseShift += mesh.triangles.Length; // BUT: this mesh.triangles may fail too!
                    // Better: get triangle count safely
                    int triCount = 0;
                    if (renderer is MeshRenderer mrr)
                        triCount = mrr.GetComponent<MeshFilter>().sharedMesh.triangles.Length;
                    else
                        triCount = ((SkinnedMeshRenderer)renderer).sharedMesh.triangles.Length;
                    baseShift += triCount;
                    continue;
                }
            }
            var materials = new List<Material>(renderer.sharedMaterials);
            for (int i = 0; i < mesh.subMeshCount; i++)
            {
                var material = (i < materials.Count ? materials[i] : materials[materials.Count - 1]);
                var part = new Part();
                var mat = new MMDMaterial();
                part.Material = mat;
                mat.Name = mat.NameEn = material.name.Replace(" (Instance)","");
                mat.DiffuseColor = Color.white;
                mat.SpecularColor = Color.clear;
                mat.AmbientColor = Color.white * 0.5f;
                mat.Shiness = 5;
                mat.CastSelfShadow = true;
                mat.DrawGroundShadow = true;
                mat.DrawSelfShadow = true;
                mat.EdgeColor = Color.black;
                mat.EdgeSize = 0.4f;
                // The writer writes the comment with no null guard, and MMD treats an empty comment as "none",
                // so every material starts out with an empty one
                mat.MetaInfo = string.Empty;

                if (material.HasProperty("_MainTex") && material.mainTexture != null)
                {
                    try
                    {
                        var tex = model.TextureList.Find(t => t.TexturePath.Contains($"/{material.mainTexture.name}.png"));
                        if (tex == null)
                        {
                            Debug.LogWarning($"{Tag} {material.name}: texture '{material.mainTexture.name}' is not in the exported "
                                             + "texture list, substituting the first texture - the surface will not look right");
                        }
                        mat.Texture = (tex ?? model.TextureList[0]);
                    }
                    catch (Exception e)
                    {
                        Debug.LogWarning($"{Tag} {material.name}: texture lookup failed ({e.Message}), "
                                         + "substituting the first texture");
                        mat.Texture = model.TextureList[0];
                    }
                }
                else
                {
                    // e.g. environment materials whose texture set is only assigned at runtime by the game
                    Debug.LogWarning($"{Tag} {material.name}: no main texture at all, substituting the first texture - "
                                     + "the surface will not look right (see UmaEnvTextureSet for environment scenes)");
                    mat.Texture = model.TextureList[0];
                }
                // Opt out for models that are meant to be used without the Blender addon: the plain MMD
                // material values set above are then left alone, which is what an unadorned export looks like
                if (Config.Instance == null || Config.Instance.PmxUmaMaterialFields)
                {
                    mat.MetaInfo = UmaMaterialComment(material, model);

                    // The uma maps stay out of MMD's sphere and toon slots, both measured by rendering them:
                    //
                    // * the uma environment map is added at the material's own _EnvRate (0.4) by the game, while
                    //   MMD's "sphere add" mode adds it at full strength with no rate to scale it - the model
                    //   came out washed out and glossy
                    // * the uma shade map (shad_c) is the colour of the shaded part of the surface, not a ramp,
                    //   so an MMD toon slot fed with it banded the model into harsh dark steps (black hair)
                    //
                    // Both maps are exported as textures and named in the comment, so a shader that understands
                    // what they are (the uma addon's) can use them properly.
                    mat.Toon = null;
                    mat.SubTexture = null;
                    mat.SubTextureType = MMDMaterial.SubTextureTypeEnum.MatSubTexOff;

                    // MMD's specular is a colour and a shininess; the uma material has a colour and a power on a
                    // different scale, so the power scales the colour down instead of the colour being used as
                    // it is (which made every part look polished).
                    var specular = PropertyColour(material, "_SpecularColor", Color.clear);
                    float specularPower = PropertyFloat(material, "_SpecularPower", 0f);
                    mat.SpecularColor = new Color(specular.r * specularPower, specular.g * specularPower,
                                                  specular.b * specularPower, 1f);
                    mat.EdgeColor = PropertyColour(material, "_OutlineColor", mat.EdgeColor);
                    mat.EdgeSize = PropertyFloat(material, "_OutlineWidth", mat.EdgeSize);
                    mat.DrawEdge = mat.EdgeSize > 0f;
                }
                part.BaseShift = baseShift + mesh.GetSubMesh(i).indexStart;
                part.TriangleIndexNum = mesh.GetSubMesh(i).indexCount;
                parts.Add(part);
            }
            baseShift += mesh.triangles.Length;
        }
        return parts.ToArray();
    }

    private static Vertex[] ReadVerticesAndTriangles(List<Renderer> renderers, List<Transform> bones, ref List<int> triangleList, Transform root)
    {
        List<Vertex> verticesList = new List<Vertex>();
        int vertexOffset = 0;

        foreach (Renderer renderer in renderers)
        {
            if (renderer is MeshRenderer mr)
            {
                var meshfilter = mr.GetComponent<MeshFilter>();
                //Cache this data to avoid copying arrays.
                var mesh = meshfilter.mesh;
                if (!mesh.isReadable)
                {
                    UmaViewerUI.Instance.ShowMessage($"Mesh {mesh.name} was not readable. Attempting to export", UIMessageType.Warning);
                    try
                    {
                        mesh = MakeReadableMeshCopy(mesh);
                    }
                    catch
                    {
                        UmaViewerUI.Instance.ShowMessage($"Export {mesh.name} Failed : Mesh is not readable", UIMessageType.Error);
                        continue;
                    }
                }
                var vertices = mesh.vertices;
                var normals = mesh.normals;
                var uv = mesh.uv;
                var uv1 = mesh.uv2;
                var uv2 = mesh.uv3;
                var colors = mesh.colors;
                var triangles = mesh.triangles;

                for (int i = 0; i < vertices.Length; i++)
                {
                    Vertex vertex = new Vertex();
                    vertex.Coordinate = renderer.transform.TransformPoint(vertices[i]);
                    vertex.Normal = normals[i];
                    vertex.UvCoordinate = new Vector2(uv[i].x, 1 - uv[i].y);

                    vertex.ExtraUvCoordinate = new Vector4[3]
                    {
                        uv1.Length > 0 ? new Vector2(uv1[i].x, 1 - uv1[i].y) : Vector2.zero,
                        uv2.Length > 0 ? new Vector2(uv2[i].x, 1 - uv2[i].y) : Vector2.zero,
                        colors.Length > 0 ? colors[i] : Color.clear
                    };

                    vertex.SkinningOperator = new SkinningOperator() { Type = SkinningType.SkinningBdef1 };
                    vertex.SkinningOperator.Param = new Bdef1() { BoneId = bones.IndexOf(renderer.transform) };
                    vertex.EdgeScale = 1;
                    verticesList.Add(vertex);
                }


                foreach (var triangle in mesh.triangles)
                {
                    triangleList.Add(triangle + vertexOffset);
                }
                vertexOffset += vertices.Length;
            }
            else if (renderer is SkinnedMeshRenderer smr)
            {
                var mesh = smr.sharedMesh;
                if (!mesh.isReadable)
                {
                    UmaViewerUI.Instance.ShowMessage($"Mesh {mesh.name} was not readable. Attempting to export", UIMessageType.Warning);
                    try
                    {
                        mesh = MakeReadableMeshCopy(mesh);
                    }
                    catch
                    {
                        UmaViewerUI.Instance.ShowMessage($"Export {mesh.name} Failed : Mesh is not readable", UIMessageType.Error);
                        continue;
                    }
                }
                var vertices = mesh.vertices;
                var normals = mesh.normals;
                var uv = mesh.uv;
                var uv1 = mesh.uv2;
                var uv2 = mesh.uv3;
                var colors = mesh.colors;
                var boneCounts = mesh.GetBonesPerVertex();
                var skinbone = smr.bones;
                var skinbones = smr.bones;
                var weights = mesh.boneWeights;
                var bakemesh = new Mesh();
                smr.BakeMesh(bakemesh,true);

                for (int i = 0; i < vertices.Length; i++)
                {
                    Vertex vertex = new Vertex();
                    vertex.Coordinate = root.InverseTransformPoint(smr.transform.TransformPoint(bakemesh.vertices[i])); 
                    vertex.Normal = normals[i];
                    vertex.UvCoordinate = new Vector2(uv[i].x, 1 - uv[i].y);
                    vertex.ExtraUvCoordinate = new Vector4[3]
                    {
                        uv1.Length > 0 ? new Vector2(uv1[i].x, 1 - uv1[i].y) : Vector2.zero,
                        uv2.Length > 0 ? new Vector2(uv2[i].x, 1 - uv2[i].y) : Vector2.zero,
                        colors.Length > 0 ? colors[i] : Color.clear
                    };

                    var boneWeight = weights[i];
                    var boneCount = boneCounts[i];

                    switch (boneCount)
                    {
                        case 0:
                            vertex.SkinningOperator = new SkinningOperator() { Type = SkinningType.SkinningBdef1 };
                            vertex.SkinningOperator.Param = new Bdef1() { BoneId = GetBoneIndex(bones, renderer.transform) };
                            break;

                        default:
                        case 1:
                            vertex.SkinningOperator = new SkinningOperator() { Type = SkinningType.SkinningBdef1 };
                            vertex.SkinningOperator.Param = new Bdef1() { BoneId = GetBoneIndex(bones, skinbone[boneWeight.boneIndex0]) };
                            break;

                        case 2:
                            vertex.SkinningOperator = new SkinningOperator() { Type = SkinningType.SkinningBdef2 };
                            vertex.SkinningOperator.Param = new Bdef2()
                            {
                                BoneId = new int[]{
                                    GetBoneIndex(bones, skinbone[boneWeight.boneIndex0]),
                                    GetBoneIndex(bones, skinbone[boneWeight.boneIndex1]),
                                },
                                BoneWeight = boneWeight.weight0
                            };
                            break;

                        case 3:
                        case 4:
                            vertex.SkinningOperator = new SkinningOperator() { Type = SkinningType.SkinningBdef4 };
                            vertex.SkinningOperator.Param = new Bdef4()
                            {
                                BoneId = new int[]{
                                    GetBoneIndex(bones, skinbone[boneWeight.boneIndex0]),
                                    GetBoneIndex(bones, skinbone[boneWeight.boneIndex1]),
                                    GetBoneIndex(bones, skinbone[boneWeight.boneIndex2]),
                                    GetBoneIndex(bones, skinbone[boneWeight.boneIndex3]),
                                },
                                BoneWeight = new float[]
                                {
                                    boneWeight.weight0,
                                    boneWeight.weight1,
                                    boneWeight.weight2,
                                    boneWeight.weight3
                                }
                            };
                            break;
                    }
                    vertex.EdgeScale = 1;
                    verticesList.Add(vertex);
                }

                foreach (var triangle in mesh.triangles)
                {
                    triangleList.Add(triangle + vertexOffset);
                }
                vertexOffset += vertices.Length;
            }
        }
        return verticesList.ToArray();
    }

    private static int GetBoneIndex(List<Transform> bones, Transform bone)
    {
        return bones.Contains(bone) ? bones.IndexOf(bone) : 0;
    }

    /// <summary> Credit to pohype: https://discussions.unity.com/t/reading-meshes-at-runtime-that-are-not-enabled-for-read-write/804189/7 </summary>
    public static Mesh MakeReadableMeshCopy(Mesh nonReadableMesh)
    {
        Mesh meshCopy = new Mesh();
        meshCopy.indexFormat = nonReadableMesh.indexFormat;

        // Handle vertices
        GraphicsBuffer verticesBuffer = nonReadableMesh.GetVertexBuffer(0);
        int totalSize = verticesBuffer.stride * verticesBuffer.count;
        byte[] data = new byte[totalSize];
        verticesBuffer.GetData(data);
        meshCopy.SetVertexBufferParams(nonReadableMesh.vertexCount, nonReadableMesh.GetVertexAttributes());
        meshCopy.SetVertexBufferData(data, 0, 0, totalSize);
        verticesBuffer.Release();

        // Handle triangles
        meshCopy.subMeshCount = nonReadableMesh.subMeshCount;
        GraphicsBuffer indexesBuffer = nonReadableMesh.GetIndexBuffer();
        int tot = indexesBuffer.stride * indexesBuffer.count;
        byte[] indexesData = new byte[tot];
        indexesBuffer.GetData(indexesData);
        meshCopy.SetIndexBufferParams(indexesBuffer.count, nonReadableMesh.indexFormat);
        meshCopy.SetIndexBufferData(indexesData, 0, 0, tot);
        indexesBuffer.Release();

        // Restore submesh structure
        uint currentIndexOffset = 0;
        for (int i = 0; i < meshCopy.subMeshCount; i++)
        {
            uint subMeshIndexCount = nonReadableMesh.GetIndexCount(i);
            meshCopy.SetSubMesh(i, new SubMeshDescriptor((int)currentIndexOffset, (int)subMeshIndexCount));
            currentIndexOffset += subMeshIndexCount;
        }

        // Recalculate normals and bounds
        meshCopy.RecalculateNormals();
        meshCopy.RecalculateBounds();

        return meshCopy;
    }
}
